// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
// import 'package:firebase_auth/firebase_auth.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkh_0yYG1vuRyDBRQ1slz4XjjE6Ws43rg',
    appId: '1:463255874757:web:a8cbe7422e75dc059714ac',
    messagingSenderId: '463255874757',
    projectId: 'praktikum9-cdddf',
    authDomain: 'praktikum9-cdddf.firebaseapp.com',
    storageBucket: 'praktikum9-cdddf.appspot.com',
    measurementId: 'G-NCRJSB00QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaQATQzcSfBRYQXUNcg6pFThC4bDXPc0g',
    appId: '1:463255874757:android:dc2d9f34ba3f30a29714ac',
    messagingSenderId: '463255874757',
    projectId: 'praktikum9-cdddf',
    storageBucket: 'praktikum9-cdddf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnAQZCDXeRqHCnnPlJutHbUM-BdZrMCnE',
    appId: '1:463255874757:ios:db48c274ab3eeaa29714ac',
    messagingSenderId: '463255874757',
    projectId: 'praktikum9-cdddf',
    storageBucket: 'praktikum9-cdddf.appspot.com',
    iosBundleId: 'com.example.tokoRumah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnAQZCDXeRqHCnnPlJutHbUM-BdZrMCnE',
    appId: '1:463255874757:ios:500f7d397ee8d6799714ac',
    messagingSenderId: '463255874757',
    projectId: 'praktikum9-cdddf',
    storageBucket: 'praktikum9-cdddf.appspot.com',
    iosBundleId: 'com.example.tokoRumah.RunnerTests',
  );
}
